### Link to the recording: 
https://utoronto.zoom.us/rec/share/7L29_fWVClsQHMRlka0cqV09cSRhydPkEeTmCAixRajAf4nXmp372KzbywiCjBc3.yGldFM7mAca2lBE6?startTime=1643220615000 (Passcode: i@Gb!7#P1W)




### References:

1. NumPy Cheat Sheet:
http://datacamp-community-prod.s3.amazonaws.com/ba1fe95a-8b70-4d2f-95b0-bc954e9071b0

2. NumPy Quick Start:
https://numpy.org/doc/stable/user/quickstart.html

3. Real Python NumPy Tutorial:
https://realpython.com/numpy-tutorial/

4. `ndarray` Methods:
https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-methods


Google Colab: https://colab.research.google.com/

In [1]:
import numpy as np

In [4]:
x = np.array([1, 2, 3])
type(x)

numpy.ndarray

In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.arange(10)
np.arange(4, 10)
np.arange(3, 10, 2)

np.zeros((4, 5))
np.ones(4)

np.linspace(0, 1, 10)

np.eye(3)

np.random.normal(size=(3, 4))



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
a = np.ones((3, 4), dtype=np.int32)

a.shape[0] # same as len(a)

a.dtype



dtype('int32')

In [31]:
x = np.eye(3)
y = np.arange(3)

y @ x # same as np.matmul
# do not use np.dot() for matrix multiplication, instead np.matmul(), or @

a = np.random.random((3, 3))
b = np.random.random((3, 3))

a * b # element-wise product
a @ b # matrix product



array([0., 1., 2.])

In [37]:
a = np.arange(9).reshape(3, 3)


a > 3   # a boolean array with the same shape as `a`

a == 3 

# boolean indexing, for accessing elements using a condition
a[ a > 3 ] = 100
 

grades = np.array([4, 5, 0, 10, 11])
ages = np.array([20, 20, 19, 21, 30])

# print the grades of students older than 20
grades[ages > 20] 



array([10, 11])

In [40]:
a = np.arange(3)
b = np.array([0, 1, 2])

np.array_equal(a, b)
np.all(a == b)


True

In [50]:
a = np.arange(12).reshape(3, 4)

print(a)

print(a.sum(axis=0))  # the axis specified will be removed (aggregated over)

print(a.argmin(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 0 0 0]


In [61]:
a = np.arange(10) + 100


a[0]
a[1]

a[-1]
a[-2]

# a[start:stop:step]

a[0:5]
a[:5]

a[5:]

a[0:8:2]

a[::2]

a[::-1] # reverse the array

array([109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [64]:
a = np.arange(12).reshape(3, 4)

a[1, 1]
a[0, :] # row 1, all cols
a[-1, :] #last row

a[0, ::2] # first row, select elements with step 2

array([0, 2])

In [71]:
a = np.arange(12).reshape(3, 4)

print(a)
print(a.T)

b = np.arange(24).reshape(2, 3, 4)
b = np.swapaxes(b, 0, -1)
b.shape


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


(4, 3, 2)

In [78]:
a = np.arange(12)
a.reshape(4, -1)  # -1 means find out yourself!

np.eye(3).reshape(-1)

np.eye(3).ravel() # flatten == .reshape(-1)

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

### Broadcasting

 for any elementwise operation, with two arrays, broadcasting will kick in:

a -> (3, 3)
b -> (3, 3)

a + b ✅


a -> (3, 3)
b -> (3, 4)

a + b ❌


a -> (3, 3)
b -> (3, 1) -> will become (3, 3) by repeating the first column

this will work because of broadcasting


 add a vector to every row/column of a matrix => avoid for loops
 you have a (N, D) array of data, and you want to find the closest row to another vector of shape (D, )
x -> (N, D)
a -> (   D) -> [broadcasting] (N, D)

(x - a) : (N, D) array

np.sum((x - a)**2, axis=1) -> array of shape N


np.sum((x - a)**2, axis=1).argmin() : the index of the closest row of x to a 




https://numpy.org/doc/stable/user/basics.broadcasting.html

